### ISSUE TITLE
 Redesign the handling of user accounts

### ISSUE THREAD

**Issue by davidruvolo51** [InControlofEffects/iceApp#22]
## The problem

At the moment, the accounts dataset is stored within the application and it isn't easy to update. This requires manually adding passwords and hashing them with the sodium package.

I would like to be able to point to the location of my user accounts database or integrate an external service. For example:

```r
iceApp(..., accounts = "path/to/db/")
```

Better yet, the app should accept a `config.yml` file. For example:

```yml
app:
   resources:
      - accounts: "/path/to/resource/"
...
```

```r
config <- read_yml("config.yml")
iceApp(..., config = config)
```
